### ISSUE TITLE
Add import method for sonata admin

### ISSUE THREAD

**Issue by nicolas-bastien** [smartbooster/etl-bundle#27]
## Goal

Use this bundle to import data from a screen in sonata admin

## Todos

- [ ] Create importTrait in Controller\Admin
- [ ] implements import method base on sonata edit style
- [ ] Add a generic form
- [ ] use transformer to extract file or textarea data
- [ ] use csv extractor and implement text extractor
- [ ] add generic template
- [ ] admin should implement configureImportColumns
- [ ] use loader to have good performance 

## To be defnied

- [ ] Implement a way to add transformer ex colums Fullname to extract to last and firstname

## Description

- Add an import action to SonataCRUD admin.
- Allow you to upload a file or copy/paste data in a textarea.
- Upload display a preview to show exactly what will be created, updated
